# Generated by Django 6.1 on 2026-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApiRest', '0002_biblioteca_nota_jogo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='metacritic_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='metacritic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
