# Generated by Django 6.1 on 2026-08-30 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApiRest', '0003_jogo_metacritic_link_jogo_metacritic_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
